### ISSUE TITLE
setup.sh issues

### ISSUE THREAD

**Issue by imnoobincoding** [dreamboat-dev/huly-project#7]
# Vulnerabilities and Suggested Improvements

### 1. Input Validation
- The username input (`non_sudo_username`) is not validated, which could lead to unexpected behavior or vulnerabilities like command injection.
- **Improvement**: Validate the username to ensure it contains only valid characters:

  ```bash
  if [[ ! "$non_sudo_username" =~ ^[a-zA-Z0-9_]+$ ]]; then
      echo "Invalid username. Only alphanumeric characters and underscores are allowed."
      exit 1
  fi
  ```

### 2. Relative Paths
- The script uses relative paths for files such as `./apt/sources.list` and `./sshd/sshd_config`. This can cause errors if the script is run from a different directory.
- **Improvement**: Convert these paths to absolute paths using a base directory variable:

  ```bash
  BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cp "${BASE_DIR}/apt/sources.list" "/etc/apt/sources.list"
  ```

### 3. Logging and Error Handling
- The script lacks logging and robust error handling, making debugging difficult.
- **Improvement**: Add logging for key operations and error handling to improve script reliability:

  ```bash
  log() {
      local message="$1"
      echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') - ${message}"
  }

  log "Starting setup_apt_repos..."
  setup_apt_repos() {
      cp "${BASE_DIR}/apt/sources.list" "/etc/apt/sources.list" || {
          log "Failed to copy sources.list. Exiting."
          exit 1
      }
      apt update
  }
  ```

### 4. Hardcoding of Versions and Repositories
- The Docker repository URL hardcodes the Debian version (`bookworm`). This can lead to compatibility issues on other Debian versions.
- **Improvement**: Detect the Debian version programmatically:

  ```bash
  DEBIAN_VERSION=$(lsb_release -cs)
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${DEBIAN_VERSION} stable" > /etc/apt/sources.list.d/docker.list
  ```

### 5. Command Verification
- The script installs Docker and related packages without verifying the success of these operations.
- **Improvement**: Add checks to verify whether Docker was installed correctly:

  ```bash
  if ! command -v docker &> /dev/null; then
      echo "Docker installation failed. Exiting."
      exit 1
  fi
  log "Docker installed successfully."
  ```

### 6. Resource-Intensive Commands
- Commands like `updatedb` and `update-command-not-found` are resource-intensive and might block other operations.
- **Improvement**: Run them in the background to minimize impact:

  ```bash
  updatedb & disown
  update-command-not-found & disown
  ```

### 7. Permissions and Ownership
- The SSH setup modifies the `.ssh` directory without ensuring ownership.
- **Improvement**: Set the correct owner for the `.ssh` directory and its contents:

  ```bash
  chown -R "${non_sudo_username}:${non_sudo_username}" "/home/${non_sudo_username}/.ssh"
  ```

### 8. Backup Configuration Files
- The script overwrites important configuration files without creating a backup.
- **Improvement**: Backup existing configurations before overwriting them:

  ```bash
  cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.$(date +%F-%T)
  cp "${BASE_DIR}/sshd/sshd_config" "/etc/ssh/sshd_config"
  ```

### 9. Service Restart
- The script enables and starts the SSH service, but restarting it ensures new configurations take effect.
- **Improvement**: Use `systemctl restart` instead of start:

  ```bash
  systemctl restart ssh.service
  ```

### 10. Cleanup with `trap`
- To handle unexpected script failures, consider using a `trap` to clean up resources or output helpful messages.
- **Improvement**:

  ```bash
  trap 'echo "An error occurred. Cleaning up..."; exit 1' ERR
  ```

> Huge plus on this one, I also need to redo some of my .sh scripts just fyi 🗡️

**Comment by dreamboat-dev** [comment]
complaints seem reasonable, will look into it

**Comment by dreamboat-dev** [comment]
Most issues have been fixed.  
Exceptions:
- `6. Resource-Intensive Commands`
  - commands aren't that resource intensive so don't see an issue with it blocking other operations
- `10. Cleanup with trap`
  - already handling script failures with `set -o errexit`
